kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-reactive-http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-reactive-http-app
  template:
    metadata:
      labels:
        app: sample-reactive-http-app
    spec:
      containers:
        - name: sample-reactive-http-app
          image: sample-reactive-http-app:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: sample-reactive-http-service
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: sample-reactive-http-app
---
kind: Route
apiVersion: route.openshift.io/v1
spec:
  to:
    kind: Service
    name: sample-reactive-http-service
    weight: 100
  port:
    targetPort: http-8081
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
