kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-reactive-http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-reactive-http-app
  template:
    metadata:
      labels:
        app: sample-reactive-http-app
    spec:
      containers:
        - name: sample-reactive-http-app
          image: sample-reactive-http-app:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: sample-reactive-http-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: sample-reactive-http-app
